---
chunk_id: discourse_topic_171141_post_431_02
source_url: https://discourse.onlinedegree.iitm.ac.in/t/171141/431
source_title: Tds-official-Project1-discrepencies
content_type: discourse
tokens: 318
username: 24ds3000090
post_number: 431
topic_id: 171141
---

-base62-sha1="hCTkBDgDY5RETIdMAkhDpLOtTex" width="690" height="168" data-dominant-color="39444A">Screenshot 2025-04-07 233513805Ã—197 9.52 KB

---

**Github repo submitted:** GitHub - wasimansari-iitm/Project-AI-Agent

**Docker repo submitted:** wasimansariiitm/my-ai-agent

The previous evaluation was successfully conducted using my Docker image, which was responding as expected. However, during the subsequent evaluation, the image was rebuilt using my GitHub repo link, and unfortunately, the `app.py` file could not be found. As a result, my evaluation logs are missing from the evaluation logs bundle.

I would like to respectfully bring this to your kind attention that the `app.py` file does exist in the repository, but it is located inside a subfolder:

https://github.com/wasimansari-iitm/Project-AI-Agent/app/app.py.

But as per the submission instructions, I provided the GitHub repo link only: https://github.com/wasimansari-iitm/Project-AI-Agent.

Humbly stating, I did not anticipate that the image will be rebuilt from the GitHub repo at a later stage due to some unforeseen circumstances. Had I known this, I would have made sure the project repo was structured appropriately to support that scenario. To be noted, that the earlier evaluation ran smoothly, and the app responded to all queries as expected.
