---
chunk_id: discourse_topic_171141_post_349_00
source_url: https://discourse.onlinedegree.iitm.ac.in/t/171141/349
source_title: Tds-official-Project1-discrepencies
content_type: discourse
tokens: 103
username: 23f2004042
post_number: 349
topic_id: 171141
---

## Post #349 by 23f2004042

**Direct Link**: [Post #349](https://discourse.onlinedegree.iitm.ac.in/t/171141/349)

@carlton and @Jivraj , for Task A i had tested before and all the test cases passed, but all my A tasks has failed with 0, In the evaluation logs, i could see that all task A tests failed due to datagen.py not available.

Could you rerun the test ?
